[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags = -Wall -Wextra
lib_deps =
    knolleary/PubSubClient@^2.8
    adafruit/DHT sensor library@^1.4
    adafruit/Adafruit Unified Sensor
    bblanchon/ArduinoJson@^7.0
